from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ReasonDiagnostic:
    code: str
    category: str
    summary: str
    next_action: str
    retry_policy: str

    def as_dict(self) -> dict[str, str]:
        return {
            "code": self.code,
            "category": self.category,
            "summary": self.summary,
            "next_action": self.next_action,
            "retry_policy": self.retry_policy,
        }


def _reason(
    code: str,
    category: str,
    summary: str,
    next_action: str,
    retry_policy: str = "inspect_before_retry",
) -> ReasonDiagnostic:
    return ReasonDiagnostic(code, category, summary, next_action, retry_policy)


_REASONS = {
    item.code: item
    for item in (
        _reason(
            "observability_append_failed",
            "observability",
            "The local operational event stream could not durably append an event.",
            "Check the event path, free space, permissions and writer lock contention.",
            "safe_after_fix",
        ),
        _reason(
            "observability_stream_invalid",
            "observability",
            "The local operational event stream failed structural validation.",
            "Preserve the file for diagnosis and start a new stream before another run.",
            "do_not_append",
        ),
        _reason(
            "observability_lifecycle_invalid",
            "observability",
            (
                "The operational event stream is structural JSON but its workflow lifecycle "
                "is invalid."
            ),
            "Inspect start, completion, ordering and correlation before trusting the run.",
            "inspect_before_retry",
        ),
        _reason(
            "observability_event_contract_invalid",
            "observability",
            "The operational stream contains duplicate event ids or an invalid event combination.",
            "Inspect event ids, components, event types and statuses before trusting the run.",
            "inspect_before_retry",
        ),
        _reason(
            "observability_event_count_mismatch",
            "observability",
            "Successful destination-event counts do not match the closed workflow totals.",
            "Inspect receipt emission and durable destination state before trusting the run.",
            "inspect_before_retry",
        ),
        _reason(
            "destination_operational_event_status_unexpected",
            "observability",
            "A destination receipt reports that its operational event was not recorded.",
            "Inspect the event sink without retrying a destination write already committed.",
            "never_retry_delivery_for_event",
        ),
        _reason(
            "destination_operational_event_context_missing",
            "observability",
            "A destination receipt is missing its run or correlation identifier.",
            "Inspect runtime event configuration and treat this run as incomplete telemetry.",
            "do_not_retry_delivery_for_event",
        ),
        _reason(
            "input_not_regular",
            "parser_containment",
            "The parser worker input is not a regular file.",
            "Stage a regular file instead of a directory, device or special filesystem object.",
            "safe_after_input_change",
        ),
        _reason(
            "input_symlink",
            "parser_containment",
            "The parser worker rejected a symbolic-link input.",
            "Resolve and stage the intended regular file through a trusted ingestion step.",
            "safe_after_input_change",
        ),
        _reason(
            "input_reparse_point",
            "parser_containment",
            "The parser worker rejected a Windows reparse-point input.",
            "Resolve and stage the intended regular file through a trusted ingestion step.",
            "safe_after_input_change",
        ),
        _reason(
            "input_too_large",
            "parser_containment",
            "The parser worker input exceeds the configured snapshot limit.",
            "Keep the file quarantined and review its size before changing the policy limit.",
            "safe_after_reviewed_policy_change",
        ),
        _reason(
            "input_changed",
            "parser_containment",
            "The source input changed while the private parser snapshot was created.",
            "Retry only from a stable immutable ingestion object and inspect concurrent writers.",
            "safe_after_input_stabilized",
        ),
        _reason(
            "containment_too_weak",
            "parser_containment",
            "No available parser worker satisfies the required containment level.",
            "Install and verify a strict backend or explicitly classify the input as trusted.",
            "safe_after_configuration_change",
        ),
        _reason(
            "backend_unavailable",
            "parser_containment",
            "The selected parser worker backend is not available on this host.",
            "Check the platform, backend binary and namespace policy before retrying.",
            "safe_after_configuration_change",
        ),
        _reason(
            "insufficient_free_space",
            "parser_containment",
            "The host has insufficient free space for a private parser snapshot.",
            "Free space in the trusted snapshot volume before retrying the unchanged input.",
            "safe_after_capacity_change",
        ),
        _reason(
            "snapshot_failed",
            "parser_containment",
            "The parser worker could not create a complete private input snapshot.",
            "Inspect snapshot storage permissions, capacity and filesystem health before retrying.",
            "inspect_before_retry",
        ),
        _reason(
            "worker_start_failed",
            "parser_containment",
            "The selected parser worker could not be started.",
            "Inspect the runtime executable and sandbox launch diagnostics before retrying.",
            "safe_after_configuration_change",
        ),
        _reason(
            "worker_timeout",
            "parser_containment",
            "The content-inspection worker exceeded its wall-time budget.",
            "Keep the file quarantined and inspect its structure before increasing any limit.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "worker_output_limit",
            "parser_containment",
            "The content-inspection worker exceeded its protocol or diagnostic output budget.",
            "Treat the parser or input as faulty and inspect it outside the production host.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "worker_termination_failed",
            "parser_containment",
            "The parser worker could not be confirmed as terminated and reaped.",
            "Quarantine the host task and inspect remaining processes before another run.",
            "do_not_retry_on_same_host_task",
        ),
        _reason(
            "worker_io_failed",
            "parser_containment",
            "The bounded parser-worker communication channel failed.",
            "Inspect host process and pipe health before retrying the same input.",
            "inspect_before_retry",
        ),
        _reason(
            "worker_failed",
            "parser_containment",
            "The parser worker exited or rejected the input without an acceptable result.",
            "Use the stable worker error code and stderr digest to diagnose it outside production.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "input_snapshot_changed",
            "parser_containment",
            "The private parser snapshot changed before its result could be accepted.",
            "Reject the result and inspect host integrity or concurrent file access.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "protocol_error",
            "parser_containment",
            "The parser worker returned data outside its strict protocol contract.",
            "Preserve bounded diagnostics and inspect worker and dependency integrity.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "request_mismatch",
            "parser_containment",
            "The parser-worker response does not match its request or input snapshot.",
            "Reject the result and inspect worker integrity before processing another file.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "source_content_unsafe",
            "input_inspection",
            "The workflow fixture failed the content-safety gate.",
            (
                "Inspect the content report and do not select a parser until the blocking risk "
                "is fixed."
            ),
            "do_not_retry_unchanged",
        ),
        _reason(
            "source_content_not_delimited_text",
            "input_inspection",
            "The workflow source was not identified as the expected delimited-text format.",
            "Check the fixture bytes and content detector before running the workflow again.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "mapping_not_fully_automatic",
            "mapping",
            "The benchmark fixture did not produce the expected fully automatic mapping.",
            "Inspect every decision and its evidence before changing an automation threshold.",
            "manual_review",
        ),
        _reason(
            "mapping_fixture_mismatch",
            "mapping",
            "The benchmark mapping differs from the fixture's expected field correspondence.",
            "Inspect matcher output, schema metadata and the fixed benchmark expectation.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "mapping_plan_incomplete",
            "plan_contract",
            "The workflow mapping plan does not contain every expected rule.",
            (
                "Inspect rejected decisions and rebuild the plan only after the missing route "
                "is proven."
            ),
            "do_not_retry_unchanged",
        ),
        _reason(
            "source_record_not_signed",
            "source_trust",
            "A staged workflow record lacks the required source authentication.",
            "Check the source signing key and protocol version before enqueueing another record.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "outbox_pending_count_mismatch",
            "local_durability",
            "The durable source outbox count disagrees with the staged batch size.",
            "Stop the run and reconcile source staging state before sending more records.",
            "inspect_before_retry",
        ),
        _reason(
            "relay_lease_count_mismatch",
            "coordination",
            "The relay did not lease the complete expected batch.",
            "Inspect relay depth, active leases and rejected records before continuing.",
            "inspect_before_retry",
        ),
        _reason(
            "destination_delivery_not_delivered",
            "destination_write",
            "A workflow delivery did not finish with a delivered receipt.",
            "Inspect the receipt reason and ledger state before deciding whether replay is safe.",
            "inspect_before_retry",
        ),
        _reason(
            "destination_audit_status_unexpected",
            "audit",
            "A delivered receipt did not contain the required successful audit outcome.",
            "Inspect the audit store without retrying a destination write that may be committed.",
            "never_retry_delivery_for_audit",
        ),
        _reason(
            "source_outbox_ack_missing",
            "local_durability",
            "The source outbox did not durably acknowledge a completed record.",
            "Inspect relay acknowledgement and outbox state; resend only the existing wire bytes.",
            "retry_existing_wire_only",
        ),
        _reason(
            "verification_query_returned_no_row",
            "destination_verification",
            "The destination verification query returned no row for an expected record.",
            "Reconcile destination and ledger state before retrying any delivery.",
            "inspect_before_retry",
        ),
        _reason(
            "audit_public_key_missing",
            "audit",
            "Signed audit verification was requested without its trusted public key.",
            "Restore the matching audit verification key and verify the existing log.",
            "do_not_retry_delivery",
        ),
        _reason(
            "destination_row_count_mismatch",
            "destination_verification",
            "The final destination row count differs from the requested workflow total.",
            "Compare destination rows with committed ledger identities before any replay.",
            "inspect_before_retry",
        ),
        _reason(
            "destination_content_mismatch",
            "destination_verification",
            "At least one delivered destination value differs from the workflow fixture.",
            "Preserve the artifacts and inspect mapping, transforms and connector writes.",
            "never_blind_retry",
        ),
        _reason(
            "ledger_commit_count_mismatch",
            "local_durability",
            "Committed ledger entries do not match the requested workflow total.",
            "Reconcile ledger entries with destination rows before attempting recovery.",
            "never_blind_retry",
        ),
        _reason(
            "source_outbox_not_empty",
            "local_durability",
            "The source outbox still contains records after workflow completion.",
            "Inspect missing acknowledgements and retry only the retained signed wire bytes.",
            "retry_existing_wire_only",
        ),
        _reason(
            "relay_not_empty",
            "coordination",
            "The relay still contains queued or leased records after workflow completion.",
            "Inspect lease ownership and downstream receipts before releasing or retrying records.",
            "inspect_before_retry",
        ),
        _reason(
            "quarantine_not_empty",
            "quarantine",
            "The sealed quarantine is not empty after an expected successful workflow.",
            "Inspect quarantine reason codes and reconcile ambiguous writes before replay.",
            "inspect_before_retry",
        ),
        _reason(
            "audit_event_count_mismatch",
            "audit",
            "Verified audit-event count does not match the requested workflow total.",
            "Inspect audit append outcomes without replaying already committed deliveries.",
            "do_not_retry_delivery_for_audit",
        ),
        _reason(
            "known_plaintext_canary_found_in_blind_state",
            "confidentiality",
            "A known fixture plaintext value appeared in a payload-blind state artifact.",
            "Stop publication, preserve evidence and inspect the responsible storage boundary.",
            "security_investigation",
        ),
        _reason(
            "source_record_count_mismatch",
            "source_read",
            "The source yielded a different record count from the requested workflow fixture.",
            "Inspect source completeness and parser behavior before trusting benchmark results.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "workflow_stage_failed",
            "workflow_internal",
            "A workflow stage raised an unexpected bounded error.",
            "Use the stage name and safe error type to diagnose it before retrying.",
            "inspect_before_retry",
        ),
        _reason(
            "operational_run_not_found",
            "observability",
            "The selected event stream contains no events for this run.",
            "Check the run id and event-file retention before treating the run as healthy.",
            "inspect_before_retry",
        ),
        _reason(
            "operational_failure_status_present",
            "observability",
            "The selected event stream contains a non-healthy status or a reason code.",
            "Inspect the status and reason counts, then diagnose the emitting component.",
            "inspect_before_retry",
        ),
        _reason(
            "operational_run_not_closed",
            "observability",
            "The selected run has an invalid, uncorrelated or out-of-order workflow lifecycle.",
            "Treat the run as interrupted and inspect durable queue and ledger state.",
            "inspect_before_retry",
        ),
        _reason(
            "operational_event_contract_invalid",
            "observability",
            "The selected run has duplicate event ids or invalid component and status semantics.",
            "Treat its counters as untrusted and inspect the local event producer.",
            "inspect_before_retry",
        ),
        _reason(
            "operational_workflow_count_mismatch",
            "observability",
            "The closed run's requested, completed, batch or successful-delivery counts disagree.",
            "Inspect missing or duplicate events and reconcile durable queue and ledger state.",
            "inspect_before_retry",
        ),
        _reason(
            "delivery_claim_in_progress",
            "coordination",
            "Another worker owns an unexpired pre-write claim.",
            "Wait for the claim lease or inspect the delivery ledger.",
            "wait",
        ),
        _reason(
            "delivery_claim_lost",
            "coordination",
            "This worker lost its fenced claim before the destination write boundary.",
            "Let the current claim owner continue; inspect the ledger if the item stalls.",
            "safe_after_current_claim",
        ),
        _reason(
            "previous_write_started_ambiguous",
            "write_ambiguity",
            "A previous worker crossed the write boundary and did not record a final outcome.",
            "Reconcile the destination by business or idempotency key before force replay.",
            "never_blind_retry",
        ),
        _reason(
            "previous_delivery_ambiguous",
            "write_ambiguity",
            "A previous delivery ended in a state where commit status is not proven.",
            "Reconcile the destination before replay unless it has a proven idempotency contract.",
            "never_blind_retry",
        ),
        _reason(
            "write_outcome_unknown",
            "write_ambiguity",
            "The connector could not prove whether the destination committed the write.",
            "Reconcile the destination, then use the authorized replay path if required.",
            "never_blind_retry",
        ),
        _reason(
            "atomic_batch_write_outcome_unknown",
            "write_ambiguity",
            "The connector could not prove whether the complete atomic batch committed.",
            "Reconcile every batch item before replay and require the original retry contract.",
            "never_blind_retry",
        ),
        _reason(
            "atomic_batch_capability_changed",
            "connector_contract",
            "The connector changed its atomic-write contract before the batch write boundary.",
            "Recreate the runtime from one stable connector configuration before retrying.",
            "safe_after_configuration_change",
        ),
        _reason(
            "destination_capability_changed",
            "connector_contract",
            "The connector changed its write contract before the scalar write boundary.",
            "Recreate the runtime from one stable connector configuration before retrying.",
            "safe_after_configuration_change",
        ),
        _reason(
            "replay_capability_changed",
            "connector_contract",
            "The connector's retry contract changed after replay authorization but before write.",
            "Keep the item quarantined and re-authorize against one stable contract.",
            "never_blind_retry",
        ),
        _reason(
            "delivery_outcome_record_failed",
            "local_durability",
            "The destination acknowledged the write, but the local ledger could not record it.",
            "Treat the write as potentially committed and repair or inspect the ledger.",
            "never_blind_retry",
        ),
        _reason(
            "sealed_spool_cleanup_failed",
            "local_cleanup",
            "Destination and ledger are committed, but the sealed quarantine copy remains.",
            "Repair or repeat only local spool cleanup; do not redeliver the record.",
            "never_retry_delivery_for_cleanup",
        ),
        _reason(
            "write_not_committed",
            "destination_write",
            "The connector proved that the destination write did not commit.",
            "Fix the destination or connector error, then retry the quarantined item.",
            "safe_to_retry",
        ),
        _reason(
            "transport_verification_failed",
            "transport_integrity",
            "Authenticated transport data could not be opened or decoded safely.",
            "Check source trust, keys, protocol versions and wire integrity.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "destination_contract_failed",
            "destination_contract",
            "The decrypted record does not satisfy the runtime's exact plan or target contract.",
            "Compare the active plan, target schema and producer version before retrying.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "destination_resolution_failed",
            "destination_lookup",
            "A destination-side lookup failed before the write boundary.",
            "Check lookup configuration, uniqueness and destination availability.",
            "safe_after_fix",
        ),
        _reason(
            "relay_wire_invalid",
            "relay_intake",
            "The relay could not parse the bounded wire record.",
            "Check protocol compatibility and source serialization.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "relay_source_authentication_failed",
            "source_trust",
            "The relay could not authenticate the source identity and signature.",
            "Check the source trust bundle, connector identity and key rotation state.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "relay_transfer_expired",
            "transfer_policy",
            "The authenticated transfer is outside its validity window.",
            "Create a new authorized transfer instead of replaying expired wire bytes.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "relay_policy_rejected",
            "transfer_policy",
            "Relay policy rejected the authenticated route metadata.",
            "Compare tenant, connector and plan digest with the active relay policy.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "relay_digest_mismatch",
            "transport_integrity",
            "Stored relay bytes no longer match their authenticated digest.",
            "Quarantine the store and investigate corruption or tampering.",
            "never_retry",
        ),
        _reason(
            "recipe_rebind_failed",
            "recipe_drift",
            "A structurally matching recipe failed current validation during exact rebind.",
            "Review schema or policy drift and approve a new recipe version if appropriate.",
            "fresh_mapping_only",
        ),
        _reason(
            "recipe_auto_reuse_suspended",
            "recipe_health",
            "Automatic reuse stopped after repeated rejected recipe executions.",
            "Inspect recipe health and approve a corrected recipe version.",
            "fresh_mapping_only",
        ),
        _reason(
            "preflight_promotable",
            "preflight",
            "A complete no-write preflight passed without review findings.",
            "The plan may proceed through the separately authorized delivery workflow.",
            "not_applicable",
        ),
        _reason(
            "preflight_not_promotable",
            "preflight",
            "Preflight did not meet the strict automatic-promotion gate.",
            "Inspect findings and run a complete scan after fixing or reviewing them.",
            "do_not_auto_promote",
        ),
        _reason(
            "no_auto_approved_mapping_rules",
            "mapping",
            "The matcher found no rules with enough deterministic evidence for automatic use.",
            "Review the suggestions, add explicit aliases or approve a manual plan.",
            "manual_review",
        ),
        _reason(
            "sampled_scan",
            "preflight",
            "Only a bounded sample was checked, so automatic promotion is disabled.",
            "Run preflight without a record limit before remembering the route.",
            "do_not_auto_promote",
        ),
        _reason(
            "empty_source",
            "source_data",
            "Preflight observed no records.",
            "Confirm the source selection and provide a non-empty input.",
            "do_not_auto_promote",
        ),
        _reason(
            "input_record_limit_exceeded",
            "blast_radius",
            "The source exceeds the explicit record budget for this run.",
            "Confirm the source selection or approve a larger record budget before delivery.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "spreadsheet_formula_cache",
            "spreadsheet_freshness",
            "Spreadsheet formula values came from an unverified workbook cache.",
            "Recalculate in a trusted spreadsheet engine or review the cached values.",
            "manual_review",
        ),
        _reason(
            "record_schema_mismatch",
            "source_contract",
            "A record contains fields absent from the inspected source schema.",
            "Inspect source drift and regenerate the plan against the current schema.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "source_schema_id_mismatch",
            "plan_binding",
            "The plan is bound to a different source schema identity.",
            "Regenerate or rebind the plan against the current source schema.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "target_schema_id_mismatch",
            "plan_binding",
            "The plan is bound to a different target schema identity.",
            "Regenerate or rebind the plan against the current target schema.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "source_schema_drift",
            "plan_binding",
            "The current source schema fingerprint differs from the plan.",
            "Inspect source drift and create a newly reviewed plan.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "target_schema_drift",
            "plan_binding",
            "The current target schema fingerprint differs from the plan.",
            "Inspect destination drift and create a newly reviewed plan.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "unknown_source_field",
            "plan_contract",
            "A mapping rule references a source field that is not in the current schema.",
            "Regenerate the plan against the current source schema.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "unknown_target_field",
            "plan_contract",
            "A mapping rule references a target field that is not in the current schema.",
            "Regenerate the plan against the current target schema.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "duplicate_target",
            "plan_contract",
            "More than one mapping rule writes the same target field.",
            "Resolve the collision and approve a plan with one writer per target field.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "unknown_transform",
            "transform",
            "A mapping rule references a transform not registered in this build.",
            "Install or implement the transform, or revise the plan.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "policy_violation",
            "information_flow",
            "A mapping route violates the current information-flow policy.",
            "Review field sensitivity and use an explicitly permitted transform or route.",
            "manual_review",
        ),
        _reason(
            "type_mismatch",
            "plan_contract",
            "A direct mapping has incompatible source and target types.",
            "Choose a reviewed transform or correct the schema types.",
            "manual_review",
        ),
        _reason(
            "required_target_unmapped",
            "destination_contract",
            "The plan leaves a required destination field without a value.",
            "Map the field or mark a proven destination-generated default in the schema.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "required_source_missing",
            "source_contract",
            "A required source field is absent from at least one record.",
            "Fix the source export or explicitly revise the source contract.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "required_target_null",
            "destination_contract",
            "The mapping produces null for a required destination field.",
            "Fix the source data or mapping before delivery.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "source_transform_failed",
            "transform",
            "A source-side transform rejected at least one record.",
            "Inspect the transform contract and the referenced source field.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "transformed_type_mismatch",
            "transform",
            "A transformed value does not satisfy the target type contract.",
            "Correct the transform or target field type before delivery.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "nullable_source_to_required_target",
            "destination_contract",
            "The source contract permits null while the destination field is required.",
            "Add a reviewed null-handling rule or correct one of the schema contracts.",
            "manual_review",
        ),
        _reason(
            "source_type_unknown",
            "source_contract",
            "A non-coercing mapping lacks a declared source type.",
            "Inspect the source with stronger type evidence before approving the route.",
            "manual_review",
        ),
        _reason(
            "foreign_key_lookup_not_exercised",
            "destination_lookup",
            "Preflight could not test a destination-side foreign-key lookup.",
            "Provide a read-only destination resolver and rerun preflight.",
            "manual_review",
        ),
        _reason(
            "foreign_key_lookup_invalid",
            "destination_lookup",
            "A foreign-key rule lacks a valid unique match column.",
            "Correct the mapping rule and prove destination uniqueness.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "foreign_key_lookup_contract_invalid",
            "destination_lookup",
            "A foreign-key rule is not backed by an exact executable relation contract.",
            "Reinspect the destination and select a proven single-column unique lookup key.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "foreign_key_lookup_source_type_unknown",
            "destination_lookup",
            "A foreign-key lookup has no declared source key type.",
            "Reinspect or explicitly type the source key before approving the lookup.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "foreign_key_lookup_type_unknown",
            "destination_lookup",
            "A foreign-key lookup has an incomplete source or destination key type contract.",
            "Reinspect both schemas or explicitly type the lookup contract before approval.",
            "manual_review",
        ),
        _reason(
            "foreign_key_lookup_type_mismatch",
            "destination_lookup",
            "The source key cannot satisfy the selected destination lookup-column type.",
            "Select a compatible unique lookup key or correct the declared schema types.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "foreign_key_lookup_input_type_mismatch",
            "destination_lookup",
            "A record value does not satisfy the selected lookup-column type.",
            "Correct the source data or its declared schema before rerunning preflight.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "foreign_key_lookup_failed",
            "destination_lookup",
            "The read-only foreign-key lookup failed during preflight.",
            "Check destination access, lookup data and uniqueness.",
            "safe_after_fix",
        ),
        _reason(
            "foreign_key_resolved_null",
            "destination_lookup",
            "A non-null business key could not be resolved to its foreign key.",
            "Create or correct the referenced destination row before delivery.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "foreign_key_resolved_type_mismatch",
            "destination_lookup",
            "A foreign-key resolver returned a value outside the target type contract.",
            "Fix the resolver or destination schema before delivery.",
            "do_not_retry_unchanged",
        ),
        _reason(
            "source_iteration_failed",
            "source_read",
            "The source connector failed while preflight was reading records.",
            "Check file stability, parser limits and connector diagnostics.",
            "safe_after_fix",
        ),
    )
}


def explain_reason(code: str) -> ReasonDiagnostic:
    known = _REASONS.get(code)
    if known is not None:
        return known
    return _reason(
        code,
        "unknown",
        "This build does not have a specific explanation for the reason code.",
        "Keep the code and surrounding metadata, then inspect the emitting component.",
        "inspect_before_retry",
    )
